name: Java Project x IR

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  java-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: nAxg3Ur2VPssDAgIGJSMFlxrWtbOkE8zEVZRYbTK0cxvMAjDT_nmvJmj74W5aMyQ07UyZdL0t0vJCVVHS6Ci_g
          mode: sidecar

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # or '21' depending on your project

      - name: Download direct dependencies only
        run: |
          mvn dependency:go-offline \
          -DexcludeTransitive=true
      # # ============= InvisiRisk Cleanup =============
      # - name: Cleanup PSE
      #   if: always()
      #   uses: invisirisk/pse-action@latest
      #   with:
      #     api_url: "https://app.dev.invisirisk.com"
      #     cleanup: "true"
      # # ============= InvisiRisk Cleanup End =============
